/**
 * Basic interface to abstract applying color palettes
 */
export interface ColorGenerator {
  /**
   * Apply a color theme generated by the tool from the given wallpaper
   * @param wallpaperPath Path to the wallpaper image that will be used as source for the color palette
   */
  setColor(wallpaperPath: string): Promise<void>;
}
